---
title: "Act 4: Regression de Poisson"
author: "Elías Garza A01284041"
date: "3/10/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importando los datos

```{r}
data<-warpbreaks
head(data,10)
```

## Histograma de rupturas

```{r}
hist(data$breaks,
     main = "Histogram of Breaks",   
     xlab = "Breaks",ylab = "Freq",             
     col = "red",              
     border = "black",               
     xlim = c(0, max(data$breaks)),   
     breaks = 20)                 
```

## Media y varianza

```{r}
mu <- mean(data$breaks)
var <- var(data$breaks)
```

## Modelo de Poisson
```{r}
poisson.model<-glm(breaks ~ wool + tension, data, family = poisson(link = "log"))
summary(poisson.model)
```

Lamentablemente vemos que la desviación residual es mayor que los grados de libertad asi que tendremos que hacer un modelo cuasipoisson.

```{r}
poisson.model2<-glm(breaks ~ wool + tension, data = data, family = quasipoisson(link = "log"))
summary(poisson.model2)
```
Sin embargo, vemos que de nuevo la desviación es considerablemente alta. 
